* MinMax-Emacs.d

A Minimal or Maximal Emacs Config Framework.

** Just  another emacs configure

For beginners, configuring Emacs can be a challenging task. The reason lies in Emacs' high degree of customizability. This matter only begins to become clear after you have spent countless hours exploring. During this process, you start to focus on your genuine needs and come to believe that Emacs is not a panacea. Subsequently, you will quietly sit down and revisit your Emacs configuration file. This process might last a long time or be relatively short if you stand on the shoulders of the community. The community offers many ready-made starter kits that can quickly set you on your way. The minmax-emacs.d project is a simple Emacs configuration framework extracted from my commonly used setup. Like other startkits, its purpose is to help beginners get started quickly. What sets it apart is that it incorporates my personal experience and understanding.

** TODO Is it for you
:LOGBOOK:
- State "TODO"       from              [2025-03-11 Tue 09:17]
:END:


* Acknowledges

- [[https://github.com/doomemacs/doomemacs][Doom Emacs]]
- [[https://github.com/syl20bnr/spacemacs][Spacemacs]]
- [[https://github.com/seagle0128/.emacs.d][Centaur Emacs]]  
- [[https://sr.ht/~ashton314/emacs-bedrock/][emacs-bedrock]]
- [[https://github.com/jamescherti/minimal-emacs.d][minimal-emacs.d]]
